### ISSUE TITLE
Firebase tools 10.7.0

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/application-starter#154]
Não realizar upgrade para 10.7.0, pois nessa versão está rolando alguns problemas como https://stackoverflow.com/questions/71937121/error-http-error-400-invalid-json-payload-received-unknown-name-skiplog-c com muita gente reclamando

**Comment by leomp12** [comment]
A versão atual já é 10.7.1 , provavelmente com isso fixado (não chequei changelog) https://www.npmjs.com/package/firebase-tools
De qualquer forma a versão aqui é 10.5.0 ainda, quando o dependabot sugerir atualizar já vai estar em uma versão com isso fixado, se for um problema do pacote mesmo.
