### ISSUE TITLE
Market CI

### ISSUE THREAD

**Issue by leomp12** [ecomplus/application-starter#4]
Precisamos de um CI pro Market pra automatizar publicação (depois de release ou talvez em cada [deploy](https://github.com/ecomplus/application-starter/blob/master/.github/workflows/deploy.yml) :thinking: ). Do lado do Market, precisaremos de:
1. Personal token para o parceiro;
2. Possibilidade de publicar/atualizar o app via PUT com link para ícone, body completo do application no modelo da E-Com Plus (`app.json`) e descrição adicional em MD (`README.md`);

**Comment by leomp12** [comment]
@talissonf pode me ajudar com isto? O Market já suportaria? Algum field necessário (apenas se for realmente necessário) que eu tenha esquecido no item 2?

**Comment by talissonf** [comment]
@leomp12 posso sim! 
Na verdade o market ja tem suporte para os dois itens da lista. Que dizer, no segundo item essa descrição adicional seria um arquivo md ou só o texto no formato?

**Comment by leomp12** [comment]
@talissonf boa!
Só o conteúdo em Markdown mesmo.

Mas vamos confirmar umas coisas aqui:
- O parceiro deve poder criar/deletar um personal token (deleter é opcional por enquanto, mas interessante pra poder resetar o token caso seja vazado ou algo do tipo) independente da sua senha (pra ele não precisar jogar a senha nos secrets do repo);
- Eu estou já iniciando com um `app_id` setado, é possível manter isto?
Ou seja o Market verifica se o ID já tá registado, assim como o slug, ambos vindo do `app.json`, se por acaso já estiverem sendo usados o Market retorna 400 e explica o erro, mas se não ele mantém ambos;
- Uma request PUT deverá criar o app se ele não existir (pelo `app_id`) ou atualizar se ele existir e pertencer ao recpectivo partner autenticado, já acontece desta forma?

Isto vai simplificar o pipeline do workflow.

**Comment by talissonf** [comment]
@leomp12 é o seguinte

>     * O parceiro deve poder criar/deletar um personal token (deleter é opcional por enquanto, mas interessante pra poder resetar o token caso seja vazado ou algo do tipo) independente da sua senha (pra ele não precisar jogar a senha nos secrets do repo);

No momento eu to gerando um token que dura 24hrs, eu não salvo esse token em momento algum no market. Só na sessão se ele logar como partner. 
Passo a salvar esse token?



>     * Eu estou já iniciando com um `app_id` setado, é possível manter isto?
>       Ou seja o Market verifica se o ID já tá registado, assim como o slug, ambos vindo do `app.json`, se por acaso já estiverem sendo usados o Market retorna 400 e explica o erro, mas se não ele mantém ambos;

Atualmente eu não aceito o app_id no post em /applications porque deixo o db gerar sequencialmente, o slug eu verifico e te retorno um 400.
Mas posso fazer a sua implementação.



>     * Uma request PUT deverá criar o app se ele não existir (pelo `app_id`) ou atualizar se ele existir e pertencer ao recpectivo partner autenticado, já acontece desta forma?

Não, ele cria só com post e só atualiza com o put, faço essa implementação.

**Comment by leomp12** [comment]
> Passo a salvar esse token?

Acho que o ideal é salvar sim, tipo um [personal token do GitHub](https://help.github.com/pt/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line), sacou? É um token pra integração contínua então OAuth complica as coisas neste caso.
Pra evitar problemas com segurança, você pode definir que este token só será válido pra publicar aplicativos, não editar o cadastro do parceiro, movimentar saldo (quando isto for implementado) e outros acessos que possam ser mais sensíveis.

Esta parte do PUT e manter `app_id`/`slug` também acho bem importante, se não vamos ter que dobrar o pipeline praticamente. Isto facilitaria muito o deploy.

**Comment by talissonf** [comment]
Ta bom vou fazer as alterações no market e te aviso

**Comment by talissonf** [comment]
@leomp12 essa parte da pronta.

**Comment by leomp12** [comment]
Aí sim @talissonf, valeu! :1st_place_medal: 

Mas não tá documentado [aqui](https://github.com/ecomclub/market), seria um PUT em `https://market.e-com.plus/v1/applications`?
Quais são os fields do body além do padrão do [modelo Application](https://developers.e-com.plus/docs/api/#/store/applications/application-object)?
Qual o header pro token? E consigo pegar o token fácil no painel do parceiro no Market?

**Comment by talissonf** [comment]
Não documentei, mas vou atualizar esses docs aí.
É um put nessa url mesmo, os fields segue o padrão do applications da store-api com algumas mudanças, [schema](https://github.com/ecomclub/market/blob/master/assets/schemas/applications.json). No headers ce manda um Authorization : barear {token}.
No market, na pagina de my-account (clica no seu nome na sidebar), tem um personalToken é só clicar pra ver, se nao tiver sido gerado ainda ele gera e salva no banco.

**Comment by leomp12** [comment]
@talissonf então vou adicionar um `category`, `description` e possivelmente um `icon`.
Mas por quê o `admin_settings` virou `json_body`?

> Na real este campo `json_body` seria pra outros fields adicionais (metadata) a princípio quando eu mexi nos SQLs do Market.

Você não acha que os fields que são apenas do Market deveriam ficar isolados dos fields pra Store API? Quando instala o app atualmente tem que sair removendo vários campos separados do body que vem do Market?

**Comment by talissonf** [comment]
> Mas por quê o `admin_settings` virou `json_body`?

Não sei, apenas virou.



> Você não acha que os fields que são apenas do Market deveriam ficar isolados dos fields pra Store API? Quando instala o app atualmente tem que sair removendo vários campos separados do body que vem do Market?

Acho que sim, mas essas coisas nunca foram bem definidas, o market só nasceu. :radioactive:

**Comment by talissonf** [comment]
#7
